version: '3'

services:
  univfoodjar:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mariadb://db:3306/univFood
      - SPRING_DATASOURCE_USERNAME=dp4455
      - SPRING_DATASOURCE_PASSWORD=6759
    volumes:
      - /Users/kimhj/Desktop/bootProjectEx/univFoodJar/upload:/Users/kimhj/Desktop/bootProjectEx/univFoodJar/upload
    depends_on:
      - db

  db:
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_DATABASE: univFood
      MYSQL_USER: dp4455
      MYSQL_PASSWORD: 6759
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - /Users/kimhj/Desktop/bootProjectEx/univFoodJar/db:/var/lib/mysql